name: "Updating website with new push"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Current working directory"
        run: echo pwd

      - name: "Installing node js"
        uses: actions/setup-node@v4
        with: 
          node-version: 22.14.0

      - name: "Installing Dependencies and Package"
        run: npm ci

      - name: "Building code"
        run: "npm run build"

      - name: Debug secrets
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Service ID: $SERVICE_ID"
          echo "Length: ${#SERVICE_ID}"

      # - uses: JorgeLNJunior/render-deploy@v1.4.6
      #   with:
      #     service_id: ${{secrets.RENDER_SERVICE_ID}}
      #     api_key: ${{secrets.RENDER_API_KEY}}
      #     wait_deploy: true

      - name: Deploy to Render via API
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Deploying to Render..."
          curl -X POST "https://api.render.com/deploy/$SERVICE_ID" \
            -H "Authorization: Bearer $API_KEY"

      
